# Generated by Django 3.1.7 on 2021-04-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210407_1750'),
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
    ]
