# Generated by Django 3.1.7 on 2021-04-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210402_2024'),
        ('products', '0002_auto_20200211_1303'),
    ]

    operations = [
    ]
